### ISSUE TITLE
Update to v2 of api

### ISSUE THREAD

**Issue by barisusakli** [julianlam/nodebb-plugin-tenor-gif#23]
https://developers.google.com/tenor/guides/migrate-from-v1#update-v2-domains

https://community.nodebb.org/topic/16590/tenor-gif/7

**Comment by julianlam** [comment]
:thinking: Google owns Tenor?

**Comment by barisusakli** [comment]
Haha no idea, maybe they acquired tenor?

**Comment by barisusakli** [comment]
yup https://techcrunch.com/2018/03/27/google-acquires-gif-platform-tenor/

**Comment by julianlam** [comment]
https://github.com/julianlam/nodebb-plugin-tenor-gif/commit/b2afc8023e659cf71308d9017df8395443880140

**Comment by julianlam** [comment]
# :rotating_light: This is a breaking change

A new API key will need to be generated.
