### ISSUE TITLE
Nodebb Chat support?

### ISSUE THREAD

**Issue by JoshPanjwani** [julianlam/nodebb-plugin-tenor-gif#28]
Hi, i was wondering if theres a way to add a "GIF" button to nodebb chats just like there is one for the default composer. Thanks!

**Comment by barisusakli** [comment]
@JoshPanjwani, this will be available in nbb 3.5.0

![image](https://github.com/julianlam/nodebb-plugin-tenor-gif/assets/2583394/a2bfb0ed-ab00-43e7-913c-6afea46e539e)
