### ISSUE TITLE
Modal not loading

### ISSUE THREAD

**Issue by exomarty** [julianlam/nodebb-plugin-tenor-gif#3]
While clicking on modal i get this error on browser console
did a few restart for rebuild but no luck
![screenshot_7](https://user-images.githubusercontent.com/10746278/40087353-7361f49c-58a2-11e8-8829-68640d7a02ff.png)

**Comment by julianlam** [comment]
What version of NodeBB are you running? You might need to upgrade to a version that supports Benchpress

**Comment by julianlam** [comment]
Specifically, you need NodeBB v1.6.0+

**Comment by exomarty** [comment]
Ok thank you. No problem then
I’m on 1.4.X 
Plugin compatibility said 1.0.x :dancer:

**Comment by julianlam** [comment]
Yes, I was not aware at the time but I've updated the compatibility string
now
